[package]
name = "rs-db"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = { version = "14.0.0", features = ["with-file-history"] }
env_logger = "0.11.3"
log = "0.4.21"
serde = { version = "1.0.203", features = ["derive"] }
bincode = "1.3.3"
